export type Category = "Living Room" | "Bedroom" | "Kitchen" | "Dining";

export type Project = {
  src: string;
  title: string;
  category: Category;
  blurb: string;
  location: string;
  size: string;
  duration: string;
  vastu: string;
  scope: string;
  brief: string;
  solution: string;
  gallery: string[];
};


export const categories: ("All" | Category)[] = [
  "All",
  "Living Room",
  "Bedroom",
  "Kitchen",
  "Dining",
];

export const projects: Project[] = [
  {
    src: "/gallery/living-room-01.jpeg",
    title: "Grand Living & Dining",
    category: "Living Room",
    blurb: "Double-height living room with fluted wood paneling and a sculpted media wall.",
    location: "Jhotwara, Jaipur",
    size: "2,800 sq. ft. duplex",
    duration: "90 Days",
    vastu: "North-East Facing Entrance, Vastu-Aligned Lounge Layout",
    scope: "Architectural Drawing & Full Turnkey Interior Delivery",
    brief: "The client wanted an open, expansive double-height space that feels luxurious yet grounded. They required a massive feature media wall, high-end seating, and Vastu-compliant spacing.",
    solution: "We installed custom fluted wood paneling extending all the way to the double-height ceiling, creating vertical continuity. We anchored the space with an onyx stone-textured media wall and soft amber LED cove lighting, optimizing furniture placement for flow and energy balance.",
    gallery: ["/gallery/living-room-01.jpeg", "/gallery/living-room-02.jpeg"],
  },
  {
    src: "/gallery/living-room-02.jpeg",
    title: "Marble & Gold Lounge",
    category: "Living Room",
    blurb: "Open-plan lounge framed by an onyx feature wall and warm cove lighting.",
    location: "Vaishali Nagar, Jaipur",
    size: "1,600 sq. ft. hall",
    duration: "65 Days",
    vastu: "East-Aligned seating, North-West window ventilation",
    scope: "Design Consultation & Premium Interior Fabrication",
    brief: "Create an intimate, elegant sitting area within a larger hall. The client requested a focal point with warm lighting, gold accents, and imported marble textures.",
    solution: "We integrated a backlit statuary onyx marble sheet flanked by gold PVD metal trims and custom timber moldings. Warm ceiling profiles and layered spot spotlights define this zone without isolating it from the rest of the layout.",
    gallery: ["/gallery/living-room-02.jpeg", "/gallery/living-room-03.jpeg"],
  },
  {
    src: "/gallery/living-room-03.jpeg",
    title: "Contemporary Sitting Room",
    category: "Living Room",
    blurb: "Plush sectional, brass accents and a sculptural floor lamp set the mood.",
    location: "C-Scheme, Jaipur",
    size: "800 sq. ft. lounge",
    duration: "45 Days",
    vastu: "Vastu-compliant Southeast lighting layout",
    scope: "Turnkey Interiors & Décor Styling",
    brief: "Design a contemporary private meeting lounge for family and business guests. It needed to feel modern, structured, and feature high-comfort premium seating.",
    solution: "We paired an organic curved boucle sectional couch with brushed brass accessories and custom matte black lighting tracks. Warm earth tones and textured plaster walls give the room a high-end, editorial gallery feel.",
    gallery: ["/gallery/living-room-03.jpeg", "/gallery/living-room-04.jpeg"],
  },
  {
    src: "/gallery/living-room-04.jpeg",
    title: "Designer Family Lounge",
    category: "Living Room",
    blurb: "U-shaped seating, textured wall panels and a soft, layered palette.",
    location: "Mansarovar, Jaipur",
    size: "1,200 sq. ft. floor",
    duration: "60 Days",
    vastu: "North-Facing main windows, East-Aligned seating",
    scope: "Turnkey Interiors",
    brief: "Develop a high-occupancy family lounge area. The space needed to incorporate a modular U-shape couch and durable, child-safe premium finishes.",
    solution: "We custom-built a U-shape sectional with spill-resistant fabric. The accent wall is lined with charcoal polystyrene panels for durability, featuring embedded warm LED strips to create a cosy, inviting evening atmosphere.",
    gallery: ["/gallery/living-room-04.jpeg", "/gallery/living-room-05.jpeg"],
  },
  {
    src: "/gallery/living-room-05.jpeg",
    title: "Tropical Accent Living",
    category: "Living Room",
    blurb: "A botanical mural and arched niches bring nature indoors.",
    location: "Malviya Nagar, Jaipur",
    size: "950 sq. ft.",
    duration: "50 Days",
    vastu: "Northeast planters & water feature placement",
    scope: "Interior Consultation & Styling",
    brief: "A unique design combining classical arches with fresh botanical themes. The client wanted a bright space filled with natural light, plants, and statement art.",
    solution: "We crafted custom drywall arches with soft inset lighting to highlight custom botanical art panels. Pale green and gold accents are layered with natural oak details, creating a refreshing oasis in the middle of Jaipur.",
    gallery: ["/gallery/living-room-05.jpeg", "/gallery/living-room-01.jpeg"],
  },
  {
    src: "/gallery/bedroom-01.jpeg",
    title: "Master Bedroom Retreat",
    category: "Bedroom",
    blurb: "Fluted headboard wall, round dresser mirror and warm ambient lighting.",
    location: "Jagatpura, Jaipur",
    size: "450 sq. ft. suite",
    duration: "40 Days",
    vastu: "South-West Bed Placement (ideal for Master Bedroom)",
    scope: "Turnkey Bedroom Interior & Wardrobes",
    brief: "Design a luxury master bedroom that feels like a boutique hotel room, with a integrated dresser, soft lighting, and extensive storage.",
    solution: "We designed a full-width fluted headboard in soft champagne fabric, flanked by suspended gold pendant lights. A circular mirror over a floating dressing console creates depth, while wardrobes are seamlessly integrated with hidden hardware.",
    gallery: ["/gallery/bedroom-01.jpeg", "/gallery/bedroom-02.jpeg"],
  },
  {
    src: "/gallery/bedroom-02.jpeg",
    title: "Suite with Walk-in Wardrobe",
    category: "Bedroom",
    blurb: "Glass-front walk-in closet flows seamlessly into the sleeping zone.",
    location: "Vaishali Nagar, Jaipur",
    size: "600 sq. ft. suite",
    duration: "55 Days",
    vastu: "South-West bed positioning, North walk-in layout",
    scope: "Turnkey Interior & Customized Storage",
    brief: "A luxurious master suite incorporating a dedicated walk-in wardrobe with glass panels and built-in vanity unit.",
    solution: "We divided the room using tinted glass wardrobes with integrated interior LED sensor lighting. The bed faces east, framed by a soft grey fabric headboard and natural ash wood panels, creating an ultra-premium, clutter-free sanctuary.",
    gallery: ["/gallery/bedroom-02.jpeg", "/gallery/bedroom-03.jpeg"],
  },
  {
    src: "/gallery/bedroom-03.jpeg",
    title: "Warm Wood Bedroom",
    category: "Bedroom",
    blurb: "Cosy lounge chair, statement art and a tactile timber feature wall.",
    location: "Jhotwara, Jaipur",
    size: "380 sq. ft.",
    duration: "35 Days",
    vastu: "Southwest sleeping orientation",
    scope: "Turnkey Interiors",
    brief: "Create a warm, woody bedroom design for the client's parents. The space required high safety, easy-to-reach storage, and warm lighting.",
    solution: "We clad the primary wall in real natural walnut veneer panels with a matte eco-wax finish. We installed indirect warm lighting and curated comfortable armchairs for a cozy reading corner, keeping pathways wide and clutter-free.",
    gallery: ["/gallery/bedroom-03.jpeg", "/gallery/bedroom-04.jpeg"],
  },
  {
    src: "/gallery/bedroom-04.jpeg",
    title: "Elegant Couple's Bedroom",
    category: "Bedroom",
    blurb: "Balanced symmetry, pendant lights and a calming neutral scheme.",
    location: "C-Scheme, Jaipur",
    size: "420 sq. ft.",
    duration: "40 Days",
    vastu: "Southwest bed positioning",
    scope: "Interior Design & Fit-out",
    brief: "A minimalist couple's bedroom with a focus on symmetry, neutral color palettes, and soft, relaxing lighting layouts.",
    solution: "We designed matching bedside tables integrated into the ash wood wall paneling. Symmetrical brushed gold pendant lights hang on both sides, casting a soft glow. Wardrobes are handleless with push-to-open German hardware.",
    gallery: ["/gallery/bedroom-04.jpeg", "/gallery/bedroom-05.jpeg"],
  },
  {
    src: "/gallery/bedroom-05.jpeg",
    title: "Bedroom with Study",
    category: "Bedroom",
    blurb: "Paneled wall, integrated study desk and floating display shelves.",
    location: "Mansarovar, Jaipur",
    size: "350 sq. ft. kids room",
    duration: "38 Days",
    vastu: "Northeast Study Desk Placement (enhances concentration)",
    scope: "Turnkey Bedroom & Study Fit-out",
    brief: "A multi-functional kids' room that incorporates a functional study desk, floating shelves, and smart storage for books.",
    solution: "We placed the study desk in the northeast corner as per Vastu principles. Floating shelves with warm LED lights sit above the desk. The bed headboard wall features playful grey-beige geometry, utilizing storage drawers under the platform bed.",
    gallery: ["/gallery/bedroom-05.jpeg", "/gallery/bedroom-06.jpeg"],
  },
  {
    src: "/gallery/bedroom-06.jpeg",
    title: "Garden-View Bedroom",
    category: "Bedroom",
    blurb: "Floor-to-ceiling glazing opens to a serene green outlook.",
    location: "Chitrakoot, Jaipur",
    size: "500 sq. ft.",
    duration: "45 Days",
    vastu: "North-facing window alignment",
    scope: "Turnkey Interior & Glazing Consultation",
    brief: "A garden-view guest suite. The goal was to merge the indoor bedroom layout with the lush outdoor garden terrace.",
    solution: "We installed slim-profile slide-fold glass doors, creating a seamless threshold. The interior palette utilizes sage green, cream bouclé, and light ash wood to reflect the colors of the garden landscape.",
    gallery: ["/gallery/bedroom-06.jpeg", "/gallery/bedroom-01.jpeg"],
  },
  {
    src: "/gallery/kitchen-01.jpeg",
    title: "Open Island Kitchen",
    category: "Kitchen",
    blurb: "Double-height modular kitchen with breakfast island and tall windows.",
    location: "Jagatpura, Jaipur",
    size: "350 sq. ft. kitchen",
    duration: "50 Days",
    vastu: "Southeast Stove Placement (Agneya Kon - essential for prosperity)",
    scope: "Architectural Consulting & Premium Modular Kitchen",
    brief: "A modern, open-concept kitchen with high ceilings. The client requested a central breakfast island and integrated premium appliances.",
    solution: "We designed a modular kitchen using Greenply BWP plywood and anti-fingerprint acrylic sheets. The hob is situated in the southeast corner. The central island is clad in Calacatta marble with an integrated prep sink and custom wooden stools.",
    gallery: ["/gallery/kitchen-01.jpeg", "/gallery/kitchen-02.jpeg"],
  },
  {
    src: "/gallery/kitchen-02.jpeg",
    title: "Modern Modular Kitchen",
    category: "Kitchen",
    blurb: "Handleless cabinetry, marble backsplash and integrated appliances.",
    location: "Vaishali Nagar, Jaipur",
    size: "240 sq. ft. kitchen",
    duration: "30 Days",
    vastu: "Southeast hob alignment, Northwest refrigerator",
    scope: "Turnkey Modular Kitchen Execution",
    brief: "Design a high-efficiency modular kitchen. The client requested complete handleless cabinet systems, premium pullouts, and marble details.",
    solution: "We implemented a G-profile handleless modular kitchen with soft-close Blum drawer systems. The backsplash is covered in book-matched white marble sheets, matched with charcoal matte cabinets for a stunning high-contrast finish.",
    gallery: ["/gallery/kitchen-02.jpeg", "/gallery/kitchen-03.jpeg"],
  },
  {
    src: "/gallery/kitchen-03.jpeg",
    title: "Kitchen & Dining Combo",
    category: "Kitchen",
    blurb: "Sage-green island kitchen opening into a jewel-toned dining space.",
    location: "C-Scheme, Jaipur",
    size: "400 sq. ft.",
    duration: "40 Days",
    vastu: "Southeast kitchen cooking zone",
    scope: "Turnkey Kitchen & Dining Interior",
    brief: "A combined kitchen and dining space that feels unified. The client preferred sage green tones and a premium built-in pantry unit.",
    solution: "We custom-fabricated sage green shaker-style cabinets with brass handles, transitioning into a jewel-toned dining area. The pantry features glass shutters and built-in profile lighting to display premium glassware.",
    gallery: ["/gallery/kitchen-03.jpeg", "/gallery/dining-01.jpeg"],
  },
  {
    src: "/gallery/dining-01.jpeg",
    title: "Luxe Dining Room",
    category: "Dining",
    blurb: "Sapphire velvet chairs, a swan wall feature and tiered chandelier.",
    location: "Malviya Nagar, Jaipur",
    size: "300 sq. ft.",
    duration: "35 Days",
    vastu: "West-aligned dining table position (ideal for family meals)",
    scope: "Turnkey Dining Room Interior & Lighting",
    brief: "Design a formal dining room for entertaining guests. It needed to feature a high-end dining table, statement lighting, and custom wall art.",
    solution: "We installed a bespoke quartz dining table with gold-coated legs, surrounded by sapphire blue velvet chairs. We highlighted the primary wall with a sculpted swan plaster panel and warm LED strip outlines, crowned by a tiered crystal chandelier.",
    gallery: ["/gallery/dining-01.jpeg", "/gallery/dining-02.jpeg"],
  },
  {
    src: "/gallery/dining-02.jpeg",
    title: "Refined Dining Nook",
    category: "Dining",
    blurb: "Paneled walls and abstract art create an intimate dining setting.",
    location: "Jhotwara, Jaipur",
    size: "180 sq. ft.",
    duration: "25 Days",
    vastu: "West-aligned family dining",
    scope: "Turnkey Dining Interior",
    brief: "Transform a small corner nook off the kitchen into a warm, intimate family dining zone with comfortable wall paneling.",
    solution: "We built custom warm-oak wall paneling with vertical grooving, framing a contemporary abstract art piece. A sleek, minimal pendant light hangs over a round oak dining table, maximizing space in a compact layout.",
    gallery: ["/gallery/dining-02.jpeg", "/gallery/living-room-03.jpeg"],
  },
  {
    src: "/gallery/guest-master-bedroom/render-01.jpeg",
    title: "Luxury Guest & Master Suites (3D Renders)",
    category: "Bedroom",
    blurb: "Photorealistic 3D visualizations blending custom fluted paneling and bespoke warm lighting.",
    location: "Vaishali Nagar, Jaipur",
    size: "1,100 sq. ft. area",
    duration: "75 Days",
    vastu: "South-West master bed orientation, North-East guest ventilation",
    scope: "3D Interior Visualizations & Space Planning",
    brief: "The client requested high-fidelity, photorealistic 3D renders of the guest and master bedrooms to pre-visualize materials, lighting balance, and space layouts.",
    solution: "We developed comprehensive 3D models of both rooms, capturing textures like fluted paneling, warm LED backlights, and customized wardrobe detailing to align precisely with their design theme.",
    gallery: [
      "/gallery/guest-master-bedroom/render-01.jpeg",
      "/gallery/guest-master-bedroom/render-02.jpeg",
      "/gallery/guest-master-bedroom/render-03.jpeg",
      "/gallery/guest-master-bedroom/render-04.jpeg",
      "/gallery/guest-master-bedroom/render-05.jpeg",
      "/gallery/guest-master-bedroom/render-06.jpeg",
      "/gallery/guest-master-bedroom/render-07.jpeg",
      "/gallery/guest-master-bedroom/render-08.jpeg",
      "/gallery/guest-master-bedroom/render-09.jpeg",
      "/gallery/guest-master-bedroom/render-10.jpeg"
    ]
  },
];
